name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: "${{ secrets.ACCESS_TOKEN }}"
    - name: Configuring security groups for deployment
      run: |
         sudo apt install awscli -y
         aws configure set aws_access_key_id "${{ secrets.ACCESS_KEY }}"
         aws configure set aws_secret_access_key "${{ secrets.SECRET_KEY }}"
         aws configure set region "${{ secrets.AWS_REGION }}"
         aws ec2 authorize-security-group-ingress --group-id ${{ secrets.GROUPID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}
    - name: Deployment on Dev-First
      run: |
         echo "security changes"
    - name: Disabling security group rule that created for deployment
      run: |
       # aws ec2 revoke-security-group-ingress --group-id ${{ secrets.GROUPID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}
