name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "security changes"
         echo "Test changes" /test/test.txt
         cat /test/test.txt
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test process
      run: |
         echo "security changes"
         echo "Test changes" /test/test.txt
         cat /test/test.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: deploy process
      run: |
         echo "security changes"
         echo "Test changes" /test/test.txt
         cat /test/test.txt
