name: Dev-app-Automatic-deployment

on:
  workflow_call: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         apt-get update
         apt-get install nginx
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         apt-get update
         apt-get install nginx
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: deploy process
      run: |
         echo "deploy process"
         apt-get update
         apt-get install nginx
  release:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: release process
      run: |
         echo "release process"
         apt-get update
         apt-get install nginx
