name: Dev-app-Automatic-deployment

on:
 push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         sudo apt-get update
         sudo apt-get install nginx
         
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         sudo apt-get update
         sudo apt-get install nginx

      
  manual_job:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Manual Job
        run: echo "new commands"
