name: Dev-app-Automatic-deployment

on:
 push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         sudo apt-get update
         sudo apt-get install nginx
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         apt-get update
         apt-get install nginx
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: deploy process
      run: |
         echo "deploy process"
         apt-get update
         apt-get install nginx

  manual_deploy:
   runs-on: ubuntu-latest
   needs: [test]
   if: github.event_name == 'workflow_dispatch'
   steps:
     - name: Manual Deploy Process
       run: |
         echo "Manually triggered deploy process"
