name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test process
      run: |
         echo "test process"
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: deploy process
      run: |
         echo "deploy process"
