name: laravel-test-check

on:
  push:
    branches: [ master ]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       token: "${{ secrets.ACCESS_TOKEN }}"
    - name: show message
      run: echo "Hi, This is our new pipeline"
