name: Dev-app-Automatic-deployment

on:
 push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         sudo apt-get update
         sudo apt-get install nginx
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         sudo apt-get update
         sudo apt-get install nginx
    - name: Early exit
      id: exit
      run: echo "test"
      continue-on-error: true
    - name: Check on failures
      if: steps.exit.outcome != 'success'
      run: exit 1
  test2:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: test process
      run: |
         echo "test process"
