name: Dev-app-Automatic-deployment

on:
 workflow_dispatch:
    inputs:
      name:
        description: "test trigger"
        default: "test"
 push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         sudo apt-get update
         sudo apt-get install nginx
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         sudo apt-get update
         sudo apt-get install nginx
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event.inputs == 'name'
    steps:
    - name: deploy process
      run: |
         echo "deploy process"
         sudo apt-get update
         sudo apt-get install nginx
