name: Dev-app-Automatic-deployment

on:
 push:
    branches: [ masterrrr ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
         sudo apt-get update
         sudo apt-get install nginx
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: test process
      run: |
         echo "test process"
         sudo apt-get update
         sudo apt-get install nginx
