name: laravel-test-check

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud & Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Creating sonar properties file
        run: |
            touch sonar-project.properties
            echo sonar.projectKey=${{ secrets.SONARPROJECTKEY }} >> sonar-project.properties
            echo sonar.organization=${{ secrets.SONARORG }} >> sonar-project.properties
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: pipeline
        run: echo "Hi, This is our new pipeline"
