name: Dev-app-Automatic-deployment

on:
  workflow_call: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build process
      run: |
         echo "build process"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test process
      run: |
         echo "test process"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy process
      run: |
         echo "deploy process"
  release:
    runs-on: ubuntu-latest
    needs: [build, test, deploy]
    steps:
    - name: release process
      run: |
         echo "release process"
