name: sonar-check

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nelonoel/branch-name@v1
      - run: echo ${BRANCH_NAME}
#      - name: Appcenter trigger
#        run: |
#         npm install -g appcenter-cli
#         appcenter login --token ${{ secrets.APPCENTERTOKEN }}
#         appcenter apps create -app Perfutil
#         appcenter build queue --app Perfutil/
