name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ test ]
jobs:
  diff:
    name: test fow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-test
        with:
          script: echo "testing exits code"
