name: sonar-check

on:
  push:
     branches: [ Humm-UK-Staging-pipeline ]
#  pull_request:
#    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch        
      - name: get branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}      
      - name: Appcenter trigger
        run: |
         npm install -g appcenter-cli
         appcenter login --token ${{ secrets.APPCENTERTOKEN }}
         appcenter apps create Perfutil/${{ steps.extract_branch.outputs.branch }}
         appcenter build queue --app Perfutil/${{ steps.extract_branch.outputs.branch }}
