name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ test ]
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Test flow
      - uses: actions/github-script@v6
        with:
          script: echo "testing exits code"
