name: Dev-app-Automatic-deployment

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment on Dev-First
      run: |
         echo "security changes"
         echo "Test changes" > test.txt
         cat test.txt
